hunter_add_package(bcos-framework)
find_package(Boost CONFIG REQUIRED log chrono system filesystem iostreams thread)
find_package(Protobuf CONFIG REQUIRED)
find_package(tbb)
find_package(bcos-framework CONFIG REQUIRED)
