hunter_add_package(bcos-crypto)
find_package(wedpr-crypto CONFIG REQUIRED)
find_package(bcos-crypto CONFIG REQUIRED)
find_package(bcos-framework CONFIG REQUIRED)
find_package(Boost CONFIG REQUIRED log program_options chrono system filesystem iostreams thread)
