include(GNUInstallDirs)
set(DESTINATION_INCLUDE_DIR "${CMAKE_INSTALL_INCLUDEDIR}/bcos-pbft")
file(COPY framework
    DESTINATION ${DESTINATION_INCLUDE_DIR}
    FILES_MATCHING PATTERN "*.h"
)

file(COPY core
    DESTINATION ${DESTINATION_INCLUDE_DIR}
    FILES_MATCHING PATTERN "*.h"
)

file(COPY pbft
    DESTINATION ${DESTINATION_INCLUDE_DIR}
    FILES_MATCHING PATTERN "*.h"
)